# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edituserui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Page(object):
    def setupUi(self, Page):
        Page.setObjectName("Page")
        Page.resize(544, 429)
        self.gridLayout = QtWidgets.QGridLayout(Page)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Page)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.fieldName = QtWidgets.QLineEdit(Page)
        self.fieldName.setObjectName("fieldName")
        self.horizontalLayout_2.addWidget(self.fieldName)
        self.checkBoxAdmin = QtWidgets.QCheckBox(Page)
        self.checkBoxAdmin.setObjectName("checkBoxAdmin")
        self.horizontalLayout_2.addWidget(self.checkBoxAdmin)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Page)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBoxId = QtWidgets.QSpinBox(Page)
        self.spinBoxId.setReadOnly(False)
        self.spinBoxId.setMinimum(1)
        self.spinBoxId.setMaximum(999999999)
        self.spinBoxId.setObjectName("spinBoxId")
        self.horizontalLayout_3.addWidget(self.spinBoxId)
        self.pushButton = QtWidgets.QPushButton(Page)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(Page)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.lineEditCardCode = QtWidgets.QLineEdit(Page)
        self.lineEditCardCode.setObjectName("lineEditCardCode")
        self.horizontalLayout_5.addWidget(self.lineEditCardCode)
        self.buttonRead = QtWidgets.QPushButton(Page)
        self.buttonRead.setCheckable(True)
        self.buttonRead.setObjectName("buttonRead")
        self.horizontalLayout_5.addWidget(self.buttonRead)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.buttonShowLogs = QtWidgets.QPushButton(Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonShowLogs.sizePolicy().hasHeightForWidth())
        self.buttonShowLogs.setSizePolicy(sizePolicy)
        self.buttonShowLogs.setObjectName("buttonShowLogs")
        self.horizontalLayout_6.addWidget(self.buttonShowLogs)
        self.buttonDelete = QtWidgets.QPushButton(Page)
        self.buttonDelete.setStyleSheet("QPushButton{\n"
"    background-color:rgb(255, 75, 75);\n"
"}")
        self.buttonDelete.setObjectName("buttonDelete")
        self.horizontalLayout_6.addWidget(self.buttonDelete)
        self.buttonSave = QtWidgets.QPushButton(Page)
        self.buttonSave.setStyleSheet("QPushButton{\n"
"    background-color:rgb(100, 255, 100);\n"
"}")
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout_6.addWidget(self.buttonSave)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonExit = QtWidgets.QPushButton(Page)
        self.buttonExit.setObjectName("buttonExit")
        self.horizontalLayout.addWidget(self.buttonExit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(6, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Page)
        self.buttonExit.clicked.connect(Page.exitPressed)
        self.buttonDelete.clicked.connect(Page.deletePressed)
        self.buttonSave.clicked.connect(Page.savePressed)
        self.buttonShowLogs.clicked.connect(Page.showLogsPressed)
        self.pushButton.clicked.connect(Page.generatePressed)
        self.buttonRead.clicked.connect(Page.readCardPressed)
        QtCore.QMetaObject.connectSlotsByName(Page)

    def retranslateUi(self, Page):
        _translate = QtCore.QCoreApplication.translate
        Page.setWindowTitle(_translate("Page", "Form"))
        self.labelTitle.setText(_translate("Page", "Edit User"))
        self.label_2.setText(_translate("Page", "Name :"))
        self.checkBoxAdmin.setText(_translate("Page", "Admin"))
        self.label_3.setText(_translate("Page", "ID :"))
        self.pushButton.setText(_translate("Page", "Auto Generate"))
        self.label.setText(_translate("Page", "Card Code :"))
        self.buttonRead.setText(_translate("Page", "Read"))
        self.buttonShowLogs.setText(_translate("Page", "Show Logs"))
        self.buttonDelete.setText(_translate("Page", "Delete"))
        self.buttonSave.setText(_translate("Page", "Save"))
        self.buttonExit.setText(_translate("Page", "< --"))

